name: apple_tensorflow_intel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyter
  - autopep8
  - pandas
  - tqdm
  - matplotlib
  - opencv
  - pip
  - seaborn
  - pip:
      - textualheatmap
      - scikit-learn
      - wordcloud
