name: apple_tensorflow_intel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - scikit-learn
  - jupyter
  - autopep8
  - pandas
  - tqdm
  - matplotlib
  - opencv
  - pip
  - seaborn
  - pip:
      - textualheatmap
      - scikit-learn==1.1.1
      - wordcloud
